### PR TITLE
post-row-reorder event added.

### PR DESCRIPTION
**Pull request by alphabrik**
We need to trigger an event after the reorder row is processed and written to the database. So I have added an post-row-reorder event trigger after the update is performed. I also added the api documentation.
I hope you'll include this in future releases.

### CODE REVIEW

**Comment by DataTables** [comment]
Nice PR - that's the first one I've had to include documentation. Thank you.

A couple of points spring to mind:

* You say "written to the database", but is that not happening async? This event is synchronous, so the write won't have been done by this point
* I think I prefer the event name `rows-reordered`
* The same could be achieved with `table.on( 'row-reorder', function () { table.one( 'draw', function () { .... } ) );` - a bit more verbose though
* Might be worth creating a common object that is passed to both the `row-reorder` and your new event to help reduce the file size slightly.

**Comment by alphabrik** [comment]
Hello, 
I think, you're right with the event name. I've updated the name, the event detail object and the documentation.
I didn't mean "written to the database" in this way. I meant "after updated the data". 
Your suggestion with listening on the event draw is a good idea, so if you don't accept this pull request, we'll try it that way. Thank you!
Patrick

**Comment by DataTables** [comment]
Hi Patrick - thanks for updating your PR and your notes. I'm happy to take it as it now stands - I can see that this would be a useful event (the `draw` option would work, but requires additional coding).

Are you happy for this change to be released under the MIT license?

**Comment by alphabrik** [comment]
Hi Allan,
the MIT license is okay. Thanks for accepting!

**Comment by DataTables** [comment]
Thank you for your contribution!

**Pull request merged**
